### ISSUE TITLE
BUG: OPPD daemon does not bind with IPv6 stack

### ISSUE THREAD

**Issue by igarny** [perfsonar/oppd#6] opened 2015-09-24 10:07 UTC
Issue can be observed on toolkit instances with latest OPPD code:

[dfn.garnizov@psmp-gn-bw-02-fra-de ~]$ netstat -nat -A inet6 | grep LISTEN
tcp        0      0 :::111                      :::\*                        LISTEN
tcp        0      0 :::80                       :::\*                        LISTEN
tcp        0      0 :::22                       :::\*                        LISTEN
tcp        0      0 :::4823                     :::\*                        LISTEN
tcp        0      0 :::443                      :::\*                        LISTEN
tcp        0      0 :::861                      :::\*                        LISTEN

**Comment by laeti-tia** [comment] 2015-09-24 10:20
Hi Ivan, can you be more specific when you say latest code?  Is it 3.4.2 or 3.5-rc2?

**Comment by igarny** [comment] 2015-09-24 12:10
Hi, Antoine....I have tested it with the code supplied by Hakan, which in his words is the current of OPPD in github.

**Comment by HakanCalimFau** [comment] 2015-09-24 14:00
OK the problem is OPPD use HTTP::Daemon Perl module.This module does not support IPv6. This class is a sublass of IO::Socket::INET and only in perl version 5.1.4 IO::Socket::INET support  Ipv4 amd IPv6. To support versions before 6.1.4 I need to check how to replace the HTTP daemon. Therefore I cannot estimate how long it will take to reoplace the daemon.

**Comment by HakanCalimFau** [comment] 2015-09-25 08:40
I commited the fix. Added dependency tp spec file. Now it should be tested. Antoine please build packages so Ivan can test it. Thanks.

**Comment by HakanCalimFau** [comment] 2015-09-25 14:44
Done some test and see that oppd kills itself when a request comes in. I see in the log:
2015/09/25 16:32:20 <INFO> perSONAR-oppd - Starting shutdown sequence
2015/09/25 16:32:20 <INFO> perSONAR-oppd - Exiting

I suggest not to use this IPv6 support . We should rollback oppd to to previous version.

**Comment by HakanCalimFau** [comment] 2015-10-21 09:18
OK it is solved. Now it works. I tested only in a IPv4 enviroment. It should be tested on IPv6. Fix is commited and packages can be built.

**Comment by laeti-tia** [comment] 2015-10-21 18:37
@igarny Can you help testing this?  I've build a debian package that is available in the snapshot repo.  I guess a nightly RPM will be built with the same correction.  Versions of those packages should be something like 3.5.0.1-something (snapshot/timestamp tag).

**Comment by igarny** [comment] 2015-10-22 13:58
In fact Hakan received a confirmation for an IPv6 globally registered address here in Germany...
will check that with him and see how I can help

**Comment by HakanCalimFau** [comment] 2015-10-23 08:38
it wokrs! I have send a echo request with perfsonar-client on Pv6:
[labor@genesis-vmdev-centos6-64 perfSONAR-client]$ ./perfsonar-client.pl --uri http://[2001:638:a000:3502::21]:8090/services/MP/BWCTL --reqfile EchoRequest.xml 
Response for EchoRequest.xml:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">soapenv:Body<nmwg:message xmlns:nmwg="http://ggf.org/ns/nmwg/base/2.0/" xmlns:nmwgr="http://ggf.org/ns/nmwg/result/2.0/" type="EchoResponse" id="id1">
    <nmwg:metadata id="meta">
      nmwg:eventType
        http://schemas.perfsonar.net/tools/admin/echo/2.0
      /nmwg:eventType
    /nmwg:metadata
    <nmwg:data id="data" metadataIdRef="meta"/>
  <nmwg:metadata id="return_meta">nmwg:eventTypesuccess.echo/nmwg:eventType/nmwg:metadata<nmwg:data metadataIdRef="return_meta" id="data_return_meta">nmwgr:datumService: MP/BWCTL is ready for call/nmwgr:datum/nmwg:data/nmwg:message/soapenv:Body/soapenv:Envelope

[labor@genesis-vmdev-centos6-64 perfSONAR-client]$ 

Oppd supports now IPv6 :-)

**Comment by arlake228** [comment] 2016-01-20 15:23
Sounds like its fixed based on last comment so closing. Feel free to re-open if i am incorrect.

**Closed as completed by arlake228** 2016-01-20 15:23 UTC
